name: Test

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"

permissions: {}

jobs:
  setup-and-test:
    name: Build and Test (Python ${{ "{{" }} matrix.python-version {{ "}}" }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python ${{ "{{" }} matrix.python-version {{ "}}" }})
        run: uv python install ${{ "{{" }} matrix.python-version {{ "}}" }})
      - name: Install Dependencies
        run: uv sync --group test
      - name: Test
        run: uv run --env-file .env pytest ./tests
      - name: Coverage
        run: uv run --env-file .env pytest --cov=src --cov-report=term-missing --junitxml=pytest.xml tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
